# Generated by Django 5.1.5 on 2025-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('company', 'Company')], default=False, max_length=20, null=True),
        ),
    ]
