# Generated by Django 5.1.5 on 2025-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='first_user',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='company',
            new_name='second_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='first_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='company',
            new_name='second_company',
        ),
    ]
