# Generated by Django 5.1.5 on 2025-02-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_chat_first_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='second_company',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='first_user',
            new_name='sender',
        ),
    ]
